### ISSUE TITLE
No exported member

### ISSUE THREAD

**Issue by elizabethheine** [lakecodes/lc-svg#1]
Getting error when importing plugin to my component: **No exported member on following:**
LcSvgComponent
LcSVGService
ILcSvgConfig

**Comment by levarcooper** [comment]
Hi Elizabeth, thanks for bringing this to our attention. With lc-svg 0.0.2+ there is no need to import the service or the component, however the ILcSvgConfig interface may still be used for strong typing as shown in the updated README.
